# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('forms', '0004_auto_20180205_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsBuilderPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cms_forms_builder_formsbuilderpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forms.Form')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
